name: Android CI

on:
  push:
    branches: [ test2 ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Build app
        uses: gradle/gradle-command-action@v2
        with:
          arguments: build
